# CircleCI configuration file
# https://circleci.com/docs/2.0/language-android
version: 2
jobs:
  build:
    working_directory: ~/kotlin-sample-app
    docker:
      - image: circleci/android:api-28
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum  "buildSrc/src/main/java/Dependencies.kt" }}-{{ checksum  "gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: Run Detekt
          command: ./gradlew detekt
      - run:
          name: Run Ktlint
          command: ./gradlew ktlint
      - run:
          name: Run Lint
          command: ./gradlew lintDebug
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum  "buildSrc/src/main/java/Dependencies.kt" }}-{{ checksum  "gradle/wrapper/gradle-wrapper.properties" }}
