# CircleCI configuration file
# https://circleci.com/docs/2.0/language-android
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    working_directory: ~/kotlin-sample-app
    docker:
      - image: circleci/android:api-28
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - run: echo "fabric.key=$FABRIC_KEY" >> local.properties
      - run: echo "fabric.secret=$FABRIC_SECRET" >> local.properties
      - run: echo "marvel.key.public=$MARVEL_KEY_PUBLIC" >> local.properties
      - run: echo "marvel.key.private=$MARVEL_KEY_PRIVATE" >> local.properties
      - restore_cache:
          key: gradle-{{ checksum "build.gradle.kts" }}
      - run:
          name: Run Detekt
          command: ./gradlew detekt
      - run:
          name: Run Ktlint
          command: ./gradlew ktlint
      - run:
          name: Run Lint
          command: ./gradlew lintDebug
      - run:
          name: Run Spotless
          command: ./gradlew spotlessKotlinCheck
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest
      - run:
          name: Generate Code Coverage
          command: ./gradlew jacocoTestReportRelease
      - run:
          name: Generate Dependency Updates
          command: ./gradlew dependencyUpdates -Drevision=release
      - store_artifacts:
          path: build/dependencyUpdates
      - codecov/upload:
          flags: unittest
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
